### ISSUE TITLE
From 0e to 1e

### ISSUE THREAD

**Issue by frons79** [Futil/foundry-mothership#17]
I am placing a series of possible fixes to be done, according to **Player's Survival Guide (PSG2-v0.10)**.

**ACTOR SHEET**
- Add CONTRACTORS type
- Add buttons to ROLL for initial STATS, SAVES, HEALTH and CREDITS values
- Change HITS label with WOUNDS
- Add CONDITIONS (pg. 21) field
- Add AFFLICTIONS (pg. 32) field to accomodate for up to five of them (Addiction / Bleeding / Cryosickness / Exhaustion / Food & Water)
- Add TRINKET and PATCH
- Add PETS field
- Add CONTRACTORS field
- Add COVER (radio button? pg. 28) and add its value to equipped armor AP's

**ITEM SHEET**
- Add CLASS type
- Add FEATURE type
- Add PETS type
- Add AFFLICTION type
- - WEAPON type
- - - Implement DAMAGE value to include also WOUND and ADV/DIS flags
- - ARMOR type
- - - Change SAVE BONUS with AP
- - - Fix FEATURES field to accomodate multiple Features
- - - Add a STATUS field with two status (i.e. functional/destroyed)

**ROLLABLE TABLES**
- Add LOADOUTS
- Add PATCHES
- Add TRINKETS
- Add WOUNDS table (pg. 29)
- Add CONTRACTORS table (pg. 41)

**Comment by hollowphoton** [comment]
Awesome feedback, we are striving to make a genuine experience for both 0e and 1e players. We've recently made a big update that addresses a lot of what's mentioned here:
- Wounds added to the system
- When 1e is selected, HITS has been renamed to WOUNDS
- Conditions have been added across 0e/1e. Conditions for the Calm house-rule, in addition to android-specific panic tables have been added as well.
- Afflictions, as mentioned here, have also been added (like Bleeding, Cryosickness, etc.)
- Pets are currently accommodated by making additional character sheets for those pets. There is also a pet-specific module available to install (from the resource-sharing channel) that allows you to add a variety of pets to characters and treat them as items.
- Loadouts, patches, and trinkets are available through resources shared on our resource-sharing channel. This content, as its proprietary to Tuesday Knight Games, will not be making an appearance in this unofficial system.
- The generic Features field for weapons/armor has been updated to split out common use-cases like Speed, Oxygen, and other item-specific features found on multiple items.

That said, there are a few things we are looking to add in future updates. We have added them to our to-do list, and will likely roll out updates in the coming months addressing them:
- Contractors: Whether its improving the Creature class, or making a class specific to contractors, this is something we are looking at.
- Character/Contractor Creation: this is something we look at creating a generic macro around, that looks for any relevant items in the world or compendiums. Like a lot of our new macros, the idea would be to provide a simple, dialog driven interface to create new characters/contractors.
- Cover: we are planning to add a pop-up dialog that shows what a player's current AP/DR would be in cover situations.
- Pets: this is something we may expand upon in the future as a dedicated item type, but for now this is likely best handled by creating a dedicated character sheet for Pets who do a lot of cool stuff :) 

There are some features requested here that we don't plan to update in the near future, but I wanted to call out:
- Functional/Destroyed: this is a neat feature, but is likely best handled by removing destroyed items/weapons/armor from the inventory of a player.

I'm closing this ticket as everything mentioned here has or will be addressed soon :) Please reach out if you have any questions!
