### ISSUE TITLE
Issue: Vertically Cut-off Weapon Text and Potential Image Misalignment on Attack Rolls

### ISSUE THREAD

**Issue by paolorodriguez** [Futil/foundry-mothership#21]
# Description

In FoundryVTT using the "MoSh - Unofficial Mothership" game system, when rolling a weapon attack using a weapon with a long name, the name of the weapon appears vertically cut-off due to the CSS applied. The developers may have constrained the height to maintain alignment with the weapon image, but this leads to an issue when the weapon name is too long.

The CSS entry that affects the text is `.mosh .rollweaponh1 { height: 34px; }`. Modifying the height to `auto` fixes the cut-off text issue, but leads to a potential misalignment problem with the weapon image.

# Steps to reproduce

1. Open Foundry VTT and start a world using the "MoSh - Unofficial Mothership" game system.
2. Create a weapon with a long name that would take more than the pre-defined height of the text, such as "Makeshift Melee Weapon".
3. Perform an attack roll with the weapon, and observe the cut-off text in the chat window.

# Expected behaviour

Long weapon names should be fully visible without being cut-off vertically, and the weapon image should remain aligned with the weapon name, regardless of the length of the name.

# Actual behaviour

Vertically cut-off text because of the constrained height, and potential image misalignment if the height constraint is removed.

# Additional information

Here's an example of the output when rolling attacks for a weapon named "Makeshift Melee Weapon":

![Long Weapon Name](https://github.com/Futil/foundry-mothership/assets/31168911/183a57b2-3a8d-4b7a-8ebf-631c4f53ca04)

```
<div class="mosh" data-actor-id="pj2kCIoh0p7YSPcn" data-item-id="1ouZ6Ds5bv9V4MQ4">
    <div class="showinfo"></div>
    <div class="showlessinfo"></div>

    <div class="rollcontainer">
        <div class="flexrow">
            <div class="rollweaponh1">Makeshift Melee Weapon
            </div>
            <div style="text-align:right"><img class="roll-image" src="icons/svg/item-bag.svg" title="Makeshift Melee Weapon"></div>
        </div>

        <div class="rollh2">Success</div>

        <div class="roll-grid">
            <div class="roll-result">4</div>
        </div>
        <div class="roll-target">
            <div class="valuetext">Target:</div>
            <div class="roll-targetbox">
                <div class="value">40</div>
            </div>
        </div>
        <div class="rollmods">
            <div class="valuetext">COMBAT (40)</div>
            <div class="valuetext">Mod (0)</div>
            <div class="valuetext">Makeshift Melee Weapon (0)</div>
        </div>
        
        <div class="roll-damage">Damage</div>
        <div>
            <div class="roll-damagebox">
                <div class="value">5</div>
            </div>
        </div>
        <div class="rollmods" style="margin-top:0px">(1d10)</div>
        <br>
        
        <div class="rollmods">Range: </div>

        

    </div></div>
```

# Suggested solution

1. Consider modifying the height value of the `.mosh .rollweaponh1` CSS entry to `auto` to allow long names to display without being cut-off.
2. Consider moving the weapon image inside the `rollweaponh1` div, or utilising an equivalent strategy, ensuring the image stays aligned correctly with the weapon name, regardless of the length of the name:

![Long Weapon Name - Suggested Fix](https://github.com/Futil/foundry-mothership/assets/31168911/70824448-1acb-436f-8a1a-cbc33df19594)

# Environment

- FoundryVTT version: Version 11 Stable Build 302
- MoSh - Unofficial Mothership RPG version: 0.3.9
- Browser: Google Chrome Version 114.0.5735.133 (Official Build) (arm64)
- OS: macOS 13.4

**Comment by hollowphoton** [comment]
Thanks for flagging! Long item/condition/armor/weapon names has been an issue before. In the most recent update, we have added some tweaks in the chat message HTML that solves for most use-cases. All chat messages whose header is related to an item name, we have added a clause that checks if the name is longer than 22 characters. If the name is longer than 22 characters, we render the chat message header with the following style settings:
`style="font-size: 0.75rem; padding-top: 7px;"`

This should fix most instances where a long name makes the text wrap onto the next line. Here's an example of this in action: 
![image](https://github.com/Futil/foundry-mothership/assets/17795348/33e5522c-ed4a-4594-b2d5-6664ac265623)
