### ISSUE TITLE
Update the Ship Sheet to the Shipbreaker's Toolkit (or provide a 1e alternative to the 0e sheet)

### ISSUE THREAD

**Issue by WisdomOfWombats** [Futil/foundry-mothership#27]
The current sheet doesn't match the sheet in the Shipbreaker's Toolkit. Currently, there is no way to enter the 1e data correctly on the ship sheet. Or is there?

**Comment by Futil** [comment]
SBT ship sheets are on our roadmap and are actively being worked on, but they aren't complete and implemented yet.

**Comment by WisdomOfWombats** [comment]
Thanks for the heads up.

**Comment by hollowphoton** [comment]
SBT sheets launched in the latest update!
