### ISSUE TITLE
"Cannot read properties" error when rolling anything

### ISSUE THREAD

**Issue by phenomen** [Futil/foundry-mothership#28]
[V11] When I roll any check, there is an error in the console.
```
caught (in promise) TypeError: undefined. Cannot read properties of null (reading 'name')
[Detected 1 package: system:mosh]
    at MothershipActor.rollCheck (actor.js:2261:159)
```

![image](https://github.com/Futil/foundry-mothership/assets/138311/101772d0-43ab-4162-bbd5-06bed4ba6ac7)

**Comment by hollowphoton** [comment]
Hello! 

What is your current setting for Macro Target? Do you have a character selected?

The system defaults to the Selected Character assigned to the current user. You can switch the options to select via token if that makes things easier.

Let me know, happy to help troubleshoot.

**Comment by hollowphoton** [comment]
To assign a character, use the menu in the lower left:
![image-2-1](https://github.com/Futil/foundry-mothership/assets/17795348/f9adf19a-a8ba-48e3-a199-f16eb7a99bd0)
It should say 'Release Character' if you've set one correctly.
