### ISSUE TITLE
Rolling with disadvantage always takes the highest result, even if lower result is a critical fail

### ISSUE THREAD

**Issue by dekelpaz** [Futil/foundry-mothership#29]
<img width="280" alt="Screenshot 2024-03-16 at 16 21 44" src="https://github.com/Futil/foundry-mothership/assets/95357879/c5ecf8ce-137b-441a-9a84-204518a6d4ba">

In the attached example, the 66 result should have been used because it is a critical failure. However, 74 was picked as it is a higher result. This means the player gets a failure, while he should have gotten a critical failure.

**Comment by dekelpaz** [comment]
Also, panic rolls with disadvantage take the lower result, while a higher results is the worst result in this case.
I'm not sure if panic rolls can be used with advantage / disadvantage, so maybe those options should just be removed?

**Comment by hollowphoton** [comment]
This has been fixed in the latest update!
