### ISSUE TITLE
Ship and Vehicle update

### ISSUE THREAD

**Issue by SeneschalArgasth** [Futil/foundry-mothership#30]
I would like to preface this with a massive thank you to all the work ya'll have done so far, its been an absolute blast to work with so far. I did notice one thing though, and that's with the recent official launch of 1e (and more specifically the Shipbreakers Toolkit) there is new stats for vehicles. I believe they use "Thrusters" "Battle" and "Systems" instead of the traditional Speed, Combat, Intellect. I'm not even sure if that is worth updating after typing this out, but here I am anyways lol. Thank you again.

**Comment by hollowphoton** [comment]
This is now live in the latest update!
