### ISSUE TITLE
Rolling for an attack with advantage doesn't roll

### ISSUE THREAD

**Issue by Tronikart** [Futil/foundry-mothership#33]
## Sometimes, when rolling with advantage and having a skill selected, nothing will happen

It mainly happens when attacking with a weapon and choosing a skill to roll with, sometimes it even errors when not selecting one.

This behavior is not seen on old weapons that have their damage properly set, which is currently not possible due to #32, however, setting it to a number doesn't fix it either.

Didn't manage to fully recreate this one with 100% success, however, here's the exception thats shown on the console + 3 lines right before that:
```actor.js:2013 User left the chooseSkill dialog with: rollString:1d100 [+], skill:FIREARMS, skillValue:15
actor.js:1046 Parsed '1d100 [+]' aiming 'low' into '{1d100,1d100}kl' 
actor.js:1345 Enriched the standard roll result. rollString: 1d100 [+],rollResult: [object Object],zeroBased: true,checkCrit: true,rollTarget: 63,comparison: <,specialRoll: 
actor.js:1021 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'includes')
    at MothershipActor.parseRollString (actor.js:1021:20)
    at MothershipActor.rollCheck (actor.js:2351:33)
```

It errors more than it works, but I'm not sure exactly why sometimes the roll comes out successfully 

## The character I was testing this on:
![image](https://github.com/Futil/foundry-mothership/assets/14989643/d029c746-d7be-4043-a450-57baa73d84b9)

## The weapon I was using to test this
![image](https://github.com/Futil/foundry-mothership/assets/14989643/752847f0-6622-43bf-9fd9-7f400cc4148f)

**Comment by hollowphoton** [comment]
This is resolved in the latest patch, and was related to the blank damage value.

**Comment by hollowphoton** [comment]
closing
