### ISSUE TITLE
Creature Sheet deletes Special Ability Damage

### ISSUE THREAD

**Issue by GreybeardGM** [Futil/foundry-mothership#36]
When I edit a special Ability on any creature's sheet, the damage value will be deleted if it is anything other then a number.

E.G. "1d10" is impossible to enter, but "10" is.
The empty damage filed works just fine, it outputs the ability, but when I enter a plain number it just throws an error and nothing else happens.

**Comment by hollowphoton** [comment]
Thanks for spotting that, I found an additional instance of the data type being a number instead of a string and patched both. This will go live when 0.5.15 gets pushed to Foundry:
https://github.com/Futil/foundry-mothership/releases/tag/0.5.15
