### ISSUE TITLE
Creature Attack Rolls for RAW to 1e

### ISSUE THREAD

**Issue by GreybeardGM** [Futil/foundry-mothership#37]
I'm trying to run a 1e game. However according to the 1e Rules creatures no longer use attack rolls, but deal damage on a player's failure (as per play example in the PSG).

It would be preferable I believe to have an option to forego attack rolls by monsters entirely and out put plain damage and wound effect directly.

My current workaround is to use "Special Abilities", but considering the other issue with that my monsters are bricked and unable to deal damage right now.

**Comment by hollowphoton** [comment]
Both options currently supported:
- To make an attack roll with a weapon, click the _Weapon Name_
- To just roll damage, click the _Damage Value_

This feature also exists on the player character sheets.

**Comment by GreybeardGM** [comment]
I feel dumb now, thank for explaining!
