### ISSUE TITLE
-[x]D[y] Macros heal instad of reduce Health

### ISSUE THREAD

**Issue by GreybeardGM** [Futil/foundry-mothership#38]
I tried using positive and negative version, E.G. +1d10 and -1d10 Health Macros, but both heal the selected Character.

**Comment by hollowphoton** [comment]
Yeah just confirmed that Foundry does not output the roll total as a negative number, and instead updates the result string only: 
![image](https://github.com/Futil/foundry-mothership/assets/17795348/34df7931-cff9-4d12-b773-a8268e97a3c1)

**Comment by hollowphoton** [comment]
We use the total, as its a number, for all of the automation - so this currently impacts all negative dice rolls. Working out a long and short term fix now.

**Comment by hollowphoton** [comment]
Cool, fix is in.
https://github.com/Futil/foundry-mothership/releases/tag/0.5.15
