### ISSUE TITLE
Warnings with Foundry v12

### ISSUE THREAD

**Issue by andrewbeard** [Futil/foundry-mothership#39]
The following warnings appear when installing the system on a Foundry v12 system:

```
The system "mosh" is using "gridDistance" which is deprecated in favor of "grid.distance".
The system "mosh" is using "gridUnits" which is deprecated in favor of "grid.units".
```

**Comment by hollowphoton** [comment]
We do not have support for v12 just yet, and just locked the system down until we are able to finish testing. Thanks for testing and relaying the notes about grid distance. This is on our to-do list now and will be addressed when we roll out support for v12.
https://github.com/Futil/foundry-mothership/releases/tag/0.5.16
