### ISSUE TITLE
Unable to input damage numbers 

### ISSUE THREAD

**Issue by Bretondragon** [Futil/foundry-mothership#42]
I can’t seem to get damage numbers to stick when I input them on weapons, it immediately wipes.

**Comment by hollowphoton** [comment]
Can you confirm which version you have installed? We resolved a bug like this in 0.5.15. If you are on an earlier version, updating should resolve the issue. 

Let us know!

**Comment by Bretondragon** [comment]
Strangely it looks like it says 0.5.1 on my end - unless there's a place to find am ore specific version number. I've been trying to keep my game systems up to date in the program, but it doesn't seem to be boosting it passed 0.5.1.

**Comment by Bretondragon** [comment]
I've manually updated it, I'm uncertain why it wasn't updating but it seems to work now!

**Comment by hollowphoton** [comment]
Cool!
