### ISSUE TITLE
Can't run the module on the new Foundry version

### ISSUE THREAD

**Issue by ferograd** [Futil/foundry-mothership#45]
Hello all,

Not sure if it is known as I've seen some posts here as recent as a month ago, but the module is not supported by Foundry V12

The module itself has a warning saying "Unsupported Core Version"

And there's a bunch of alerts like the following:

Mosh Unofficial Mothership:
The system "mosh" is using "gridDistance" which is deprecated in favor of "grid.distance".
The system "mosh" is using "gridUnits" which is deprecated in favor of "grid.units".

Any idea if the author is still supporting this to get it integrated into the new version of Foundry?
I'm really itching to try this TTRPG out, but all of my friends are not local, so a play at the table is not possible.

Thanks in advance.

**Comment by ferograd** [comment]
Scrap that I guess.

Just seen that its part of the active development roadmap to provide support for V12

**Comment by hollowphoton** [comment]
Yep, we've soft locked the system to v11 for now. V12 support is in active development. If you want more up to date chat, news, or want to participate in development polls I recommend you join our discord. It's linked on the main page :)
