### ISSUE TITLE
Can't install it through Foundry

### ISSUE THREAD

**Issue by EndlessAtena** [Futil/foundry-mothership#6]
Firstly, I tried to do it in a classic way, through the app. Secondly, I tried to install it manually, downloading files from zip file into directory. No results. I see this error, when I try to install it through system:

"Installation failed: An unexpected error occured when downloading file htttps://github/Futil/foundry-mothership/archive/master.zip: request to https://codeload.github/Futil/foundry-mothership/zip/master failed, reason: connect ECONNREFUSED 127.0.0.1:443"

Please help.

**Comment by Futil** [comment]
I'll look into it tomorrow, and get back to you!

**Comment by EndlessAtena** [comment]
So, is there any news?)

**Comment by Futil** [comment]
Sorry, I meant to respond to this. I haven't been able to recreate this issue, and I suspect if it's still happening (Try it again!) it's likely an issue on Foundry's side. Let me know if you get it working.

**Comment by Futil** [comment]
It may also be an issue with your network blocking or being blocked by github in some way. I do not know a way around this.

**Comment by Futil** [comment]
If it still doesn't work, download this file: https://github.com/Futil/foundry-mothership/archive/refs/tags/0.1.7b.zip
