### ISSUE TITLE
System forced to 1e ed

### ISSUE THREAD

**Issue by JhaelenTerear** [Futil/foundry-mothership#9]
Hi,

Since the last update, the system is locked in 1e ed and there are no more toggles in system options to set back to 0 edition.

**Comment by Futil** [comment]
I'll take a look, what version of the module does it say you are on?

**Comment by JhaelenTerear** [comment]
![image](https://user-images.githubusercontent.com/58259514/148825940-82729d51-d7dd-45ff-83f5-838ac36f95c3.png)

**Comment by JhaelenTerear** [comment]
![image](https://user-images.githubusercontent.com/58259514/148826068-fb090dcd-0c6e-4667-a0f1-702b1805229f.png)

**Comment by JhaelenTerear** [comment]
![image](https://user-images.githubusercontent.com/58259514/148826145-1dd3a408-d024-4787-a19d-22ae7a814b09.png)

**Comment by JhaelenTerear** [comment]
Sorry for the french in screenshots :D !

**Comment by Futil** [comment]
Sorry for the delay, I was working my day job. I just pushed a fix for this, sorry for any inconvenience and thanks for the report!

**Comment by JhaelenTerear** [comment]
No problem, my next game is next sunday. Thanks for the fix (and for the system !), it did the trick.
